const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),mysql=require('mysql2/promise');
const PORT=Number(process.env.PORT||3000),ROOT=path.join(__dirname,'dist');
const ADMIN_USERNAME=process.env.ADMIN_USERNAME||'Admin',ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'Admin123';
const sessions=new Map(),memory={movies:new Map(),slides:new Map(),settings:{siteSettings:{},customSections:[]}};let pool=null;
const parse=(v,f)=>{try{return v?JSON.parse(v):f}catch(_){return f}},slug=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
function send(res,status,body,extra={}){res.writeHead(status,{'Content-Type':typeof body==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(typeof body==='string'?body:JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>5e6)reject(Error('Request too large'))});req.on('end',()=>resolve(parse(s,{})));req.on('error',reject)})}
function token(req){let a=String(req.headers.authorization||'');return a.startsWith('Bearer ')?a.slice(7):''}
function admin(req,res){let t=token(req),s=sessions.get(t);if(!s||s<Date.now()){if(t)sessions.delete(t);send(res,401,{error:'Admin authentication required'});return false}return true}
async function setup(){let d=process.env.DATABASE_URL||process.env.DRIZZLE_DATABASE_URL;if(!d)return;pool=mysql.createPool(d);await pool.query(`CREATE TABLE IF NOT EXISTS agastream_movies (id VARCHAR(160) PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL,poster LONGTEXT,meta VARCHAR(255),voice VARCHAR(255),genre VARCHAR(120),sections TEXT,description TEXT,watch_url TEXT,download_url TEXT,trailer_url TEXT,video_url TEXT,content_type VARCHAR(20) NOT NULL DEFAULT 'movie',episodes TEXT,is_new TINYINT(1) NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);await pool.query(`CREATE TABLE IF NOT EXISTS agastream_slides (id VARCHAR(160) PRIMARY KEY,title VARCHAR(255) NOT NULL,year VARCHAR(20),genre VARCHAR(120),interpreter VARCHAR(255),image_url LONGTEXT,watch_url TEXT,description TEXT,content_type VARCHAR(20),rating VARCHAR(20),position INT NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);await pool.query(`CREATE TABLE IF NOT EXISTS agastream_settings (id TINYINT PRIMARY KEY,payload LONGTEXT NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`)}
async function rows(q,p=[]){if(!pool)return null;let [r]=await pool.query(q,p);return r}
async function catalog(){if(!pool)return{movies:[...memory.movies.values()],slides:[...memory.slides.values()].sort((a,b)=>a.position-b.position),settings:memory.settings.siteSettings,customSections:memory.settings.customSections};let ms=await rows('SELECT * FROM agastream_movies ORDER BY updated_at DESC'),ss=await rows('SELECT * FROM agastream_slides ORDER BY position ASC,updated_at ASC'),sr=await rows('SELECT payload FROM agastream_settings WHERE id=1'),saved=sr&&sr[0]?parse(sr[0].payload,{}):{};return{movies:ms.map(r=>({adminId:r.id,catalogKey:r.id,title:r.title,poster:r.poster||'',meta:r.meta||'',voice:r.voice||'',genre:r.genre||'',section:parse(r.sections,[]),desc:r.description||'',link:r.watch_url||'',download:r.download_url||'',trailer:r.trailer_url||'',video:r.video_url||'',type:r.content_type||'movie',episodes:parse(r.episodes,[]),isNew:!!r.is_new})),slides:ss.map(r=>({id:r.id,title:r.title,year:r.year||'',genre:r.genre||'',interpreter:r.interpreter||'',img:r.image_url||'',link:r.watch_url||'',desc:r.description||'',type:r.content_type||'movie',rating:r.rating||'8.6'})),settings:saved.siteSettings||{},customSections:saved.customSections||[]}}
async function saveMovie(m){let id=String(m.adminId||m.catalogKey||'movie-'+Date.now()),r={...m,adminId:id,catalogKey:id,slug:slug(m.title),type:m.type==='series'?'series':'movie',episodes:m.type==='series'?(m.episodes||[]):[]};if(!pool){memory.movies.set(id,r);return r}await pool.query(`INSERT INTO agastream_movies (id,title,slug,poster,meta,voice,genre,sections,description,watch_url,download_url,trailer_url,video_url,content_type,episodes,is_new) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),slug=VALUES(slug),poster=VALUES(poster),meta=VALUES(meta),voice=VALUES(voice),genre=VALUES(genre),sections=VALUES(sections),description=VALUES(description),watch_url=VALUES(watch_url),download_url=VALUES(download_url),trailer_url=VALUES(trailer_url),video_url=VALUES(video_url),content_type=VALUES(content_type),episodes=VALUES(episodes),is_new=VALUES(is_new)`,[id,r.title,r.slug,r.poster||'',r.meta||'',r.voice||'',r.genre||'',JSON.stringify(r.section||[]),r.desc||'',r.link||'',r.download||'',r.trailer||'',r.video||'',r.type,JSON.stringify(r.episodes||[]),r.isNew?1:0]);return r}
async function saveSlide(s){let id=String(s.id||'slide-'+Date.now()),c=await catalog(),position=Number.isFinite(s.position)&&s.position>=0?s.position:c.slides.length,r={...s,id,position};if(!pool){memory.slides.set(id,r);return r}await pool.query(`INSERT INTO agastream_slides (id,title,year,genre,interpreter,image_url,watch_url,description,content_type,rating,position) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),year=VALUES(year),genre=VALUES(genre),interpreter=VALUES(interpreter),image_url=VALUES(image_url),watch_url=VALUES(watch_url),description=VALUES(description),content_type=VALUES(content_type),rating=VALUES(rating),position=VALUES(position)`,[id,r.title,r.year||'',r.genre||'',r.interpreter||'',r.img||'',r.link||'',r.desc||'',r.type||'movie',r.rating||'8.6',position]);return r}
async function settings(siteSettings,customSections){let p=JSON.stringify({siteSettings:siteSettings||{},customSections:customSections||[]});memory.settings={siteSettings:siteSettings||{},customSections:customSections||[]};if(pool)await pool.query('INSERT INTO agastream_settings (id,payload) VALUES (1,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload)',[p])}
function staticFile(req,res){let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p==='/')p='/index.html';let f=path.resolve(ROOT,'.'+p);if(!f.startsWith(ROOT))f=path.join(ROOT,'index.html');try{if(!fs.statSync(f).isFile())f=path.join(ROOT,'index.html')}catch(_){f=path.join(ROOT,'index.html')}let ext=path.extname(f),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res)}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x');if(u.pathname==='/api/health')return send(res,200,{ok:true,database:!!pool});if(u.pathname==='/api/catalog'&&req.method==='GET')return send(res,200,await catalog());if(u.pathname==='/api/admin/login'&&req.method==='POST'){let b=await body(req);if(b.username!==ADMIN_USERNAME||b.password!==ADMIN_PASSWORD)return send(res,401,{error:'Incorrect username or password'});let t=crypto.randomBytes(32).toString('hex');sessions.set(t,Date.now()+43200000);return send(res,200,{token:t})}if(u.pathname.startsWith('/api/admin/')){if(!admin(req,res))return;if(u.pathname==='/api/admin/catalog'&&req.method==='POST')return send(res,200,await saveMovie(await body(req)));if(u.pathname.startsWith('/api/admin/catalog/')&&req.method==='DELETE'){let id=decodeURIComponent(u.pathname.split('/').pop());if(pool)await pool.query('DELETE FROM agastream_movies WHERE id=?',[id]);else memory.movies.delete(id);return send(res,200,{ok:true})}if(u.pathname==='/api/admin/slides'&&req.method==='POST')return send(res,200,await saveSlide(await body(req)));if(u.pathname.startsWith('/api/admin/slides/')&&req.method==='DELETE'){let id=decodeURIComponent(u.pathname.split('/').pop());if(pool)await pool.query('DELETE FROM agastream_slides WHERE id=?',[id]);else memory.slides.delete(id);return send(res,200,{ok:true})}if(u.pathname==='/api/admin/slides/reorder'&&req.method==='POST'){let b=await body(req);for(let i=0;i<(b.ids||[]).length;i++)if(pool)await pool.query('UPDATE agastream_slides SET position=? WHERE id=?',[i,b.ids[i]]);else if(memory.slides.has(b.ids[i]))memory.slides.get(b.ids[i]).position=i;return send(res,200,{ok:true})}if(u.pathname==='/api/admin/settings'&&req.method==='PUT'){let b=await body(req);await settings(b.siteSettings,b.customSections);return send(res,200,{ok:true})}return send(res,404,{error:'Admin endpoint not found'})}if(req.method==='GET'||req.method==='HEAD')return staticFile(req,res);return send(res,405,{error:'Method not allowed'})}catch(e){console.error(e);send(res,500,{error:'Server error'})}});
setup().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log(`AgaStream server listening on ${PORT}; database=${!!pool}`))).catch(e=>{console.error('Database setup failed',e);process.exit(1)});
